// [x] All Auth Done
export const GET_ERROR="GET_ERROR";
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const FOREGT_PASSWORD = "FOREGT_PASSWORD";
export const VERIFY_PASSWORD = "VERIFY_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

// Users
export const GET_CURERNT_USER = "GET_CURERNT_USER";
export const GET_MENTOR = "GET_MENTOR";
export const GET_ALL_MENTORS = "GET_ALL_MENTORS";
export const GET_SUGGESTION_MENTORS = "GET_SUGGESTION_MENTORS";
export const ADD_MENTOR_TO_WISHLIST="ADD_MENTOR_TO_WISHLIST";
export const REMOVE_MENTOR_FROM_WISHLIST="REMOVE_MENTOR_FROM_WISHLIST";
export const FOLLOW_MENTOR="FOLLOW_MENTOR";
export const UNFOLLOW_MENTOR="UNFOLLOW_MENTOR";

export const GET_FEED = "GET_FEED";

// [x] Create,
export const CREATE_NEW_POST = "CREATE_NEW_POST";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const SHARE_POST = "SHARE_POST";


export const CREATE_NEW_COMMENT = "CREATE_NEW_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const ADD_REACTION = "ADD_REACTION";
export const REMOVE_REACTION = "REMOVE_REACTION";
export const GET_REACTIONS = "GET_REACTIONS";

// [x] Create,
export const CREATE_NEW_QUESTION = "CREATE_NEW_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";

export const CREATE_NEW_ANSWER = "CREATE_NEW_ANSWER";
export const GET_ANSWERS = "GET_ANSWERS";
export const UPDATE_ANSWER = "UPDATE_ANSWER";
export const DELETE_ANSWER = "DELETE_ANSWER";

export const HELPFUL = "HELPFUL";
export const UNHELPFUL = "UNHELPFUL";

export const SAVE_POST = "SAVE_POST";
export const UNSAVE_POST = "UNSAVE_POST";
export const GET_SAVED_POSTS = "GET_SAVED_POSTS";

export const SAVE_QUESTION = "SAVE_QUESTION";
export const UNSAVE_QUESTION = "UNSAVE_QUESTION";
export const GET_SAVED_QUESTIONS = "GET_SAVED_QUESTIONS";
